-- ============================================================================
-- seed_tour_travel.sql — Tour & Travel niche DATA for ONE fresh client
-- ============================================================================
-- WaCRM / Replora. Run this AFTER install.sql (schema) and AFTER creating the
-- client's auth user. It seeds the Tour & Travel scaffolding every client
-- shares: custom fields, the sales pipeline + its stages, and lead tags.
--
-- HOW TO RUN
--   1. Run install.sql first (creates all tables + RLS).
--   2. Supabase Dashboard -> Authentication -> Add User (the client account).
--   3. FIND-AND-REPLACE every occurrence of  CLIENT_USER_ID  in THIS file with
--      that new auth user's UUID (Dashboard -> Authentication -> Users -> copy
--      the id). Then paste the whole file into the SQL Editor and run.
--
-- SAFE TO RE-RUN (idempotent)
--   Every insert is guarded by WHERE NOT EXISTS on (user_id, name), so running
--   this twice never creates duplicates. No table here has a UNIQUE(user_id,
--   name) constraint, so the guard — not ON CONFLICT — is what prevents dupes.
--
-- RESELL RULES HONOURED
--   * Zero hardcoded UUIDs. The only id is the CLIENT_USER_ID you paste in.
--     The pipeline's id is generated by Postgres and looked up BY NAME so its
--     stages attach to the right pipeline without any baked-in uuid.
--   * References are name-based throughout.
--
-- INTENTIONALLY NOT SEEDED (per-client, filled elsewhere — do NOT add here)
--   * destinations — each client's own tour packages. Added via the Catalogue
--     UI or CSV/XLSX import, not seeded from the master's test rows.
--   * whatsapp_config business/AI values (business_name, support_phone, upi_id,
--     payment_qr_url, payment_note, ai_* , welcome_*, ooo_*). These are secrets
--     / per-client settings the client enters in Settings. The master's
--     encrypted ai_api_key is bound to the master's ENCRYPTION_KEY and would be
--     useless — and unsafe — under a different client's key.
--   * automations (e.g. WF3 Booking-Confirmation) — deferred; added separately
--     once the payment-verify lifecycle is wired.
--
-- MATCHES LIVE MASTER (source of truth), not the doc: 8 custom fields. The doc
-- lists a 9th, `quoted_price`, which was never created in the master DB, so it
-- is intentionally omitted here.
-- ============================================================================

-- ============================================================
-- CUSTOM FIELDS (8) — the Tour & Travel lead attributes.
-- field_type ∈ text | number | date | url | select.
-- select fields carry field_options as a JSONB string array.
-- ============================================================
INSERT INTO custom_fields (user_id, field_name, field_type, field_options)
SELECT 'CLIENT_USER_ID'::uuid, v.field_name, v.field_type, v.field_options::jsonb
FROM (VALUES
  ('tour_interest',          'select', '["Domestic","International","Adventure","Honeymoon","Corporate","Pilgrimage"]'),
  ('travel_dates',           'date',   NULL),
  ('group_size',             'number', NULL),
  ('budget_range',           'select', '["Under ₹25k","₹25k–₹50k","₹50k–₹1L","₹1L–₹2L","Above ₹2L"]'),
  ('booking_status',         'select', '["Inquiry","Quoted","Confirmed","Completed","Cancelled"]'),
  ('destination_preference', 'text',   NULL),
  ('itinerary_link',         'url',    NULL),
  ('travel_stage',           'select', '["upcoming","ongoing","completed"]')
) AS v(field_name, field_type, field_options)
WHERE NOT EXISTS (
  SELECT 1 FROM custom_fields cf
  WHERE cf.user_id = 'CLIENT_USER_ID'::uuid
    AND cf.field_name = v.field_name
);

-- ============================================================
-- TAGS (5) — lead lifecycle labels.
-- NOTE: quoted-sent keeps the master's #0084ff chip colour (legacy brand).
-- It is only a tag chip colour, not the app's CSS primary (#6366F1).
-- ============================================================
INSERT INTO tags (user_id, name, color)
SELECT 'CLIENT_USER_ID'::uuid, v.name, v.color
FROM (VALUES
  ('new-inquiry',         '#3b82f6'),
  ('quoted-sent',         '#0084ff'),
  ('confirmed-traveller', '#10b981'),
  ('review-requested',    '#8b5cf6'),
  ('vip-traveller',       '#f97316')
) AS v(name, color)
WHERE NOT EXISTS (
  SELECT 1 FROM tags t
  WHERE t.user_id = 'CLIENT_USER_ID'::uuid
    AND t.name = v.name
);

-- ============================================================
-- PIPELINE + STAGES (6) — the sales board.
-- The pipeline id is generated by Postgres and looked up BY NAME so stages
-- attach correctly with no hardcoded uuid. Wrapped in a DO block so the
-- generated id can be captured into a variable.
-- ============================================================
DO $$
DECLARE
  v_pipeline_id uuid;
BEGIN
  SELECT id INTO v_pipeline_id
  FROM pipelines
  WHERE user_id = 'CLIENT_USER_ID'::uuid
    AND name = 'Tour & Travel Pipeline'
  LIMIT 1;

  IF v_pipeline_id IS NULL THEN
    INSERT INTO pipelines (user_id, name)
    VALUES ('CLIENT_USER_ID'::uuid, 'Tour & Travel Pipeline')
    RETURNING id INTO v_pipeline_id;
  END IF;

  INSERT INTO pipeline_stages (pipeline_id, name, position, color)
  SELECT v_pipeline_id, v.name, v.position, v.color
  FROM (VALUES
    ('New Inquiry',       0, '#3b82f6'),
    ('Itinerary Sent',    1, '#06b6d4'),
    ('Follow-Up',         2, '#f97316'),
    ('Booking Confirmed', 3, '#22c55e'),
    ('Trip Ongoing',      4, '#8b5cf6'),
    ('Post-Trip',         5, '#eab308')
  ) AS v(name, position, color)
  WHERE NOT EXISTS (
    SELECT 1 FROM pipeline_stages s
    WHERE s.pipeline_id = v_pipeline_id
      AND s.name = v.name
  );
END $$;
